### ISSUE TITLE
Missing HTTPS

### ISSUE THREAD

**Issue by Danappelxx** [kerrmarin/luath#1]
Cool project! Something that jumps right out to me though is that the API is http-only (no ssl). This means that it has to be whitelisted on iOS, which is mildly inconvenient.

**Comment by kerrmarin** [comment]
Hey man :) Thanks for giving it a spin 🙃 . I've enabled HTTPS for https://luath.org (not www.). I'll work on adding www.luath.org over the week 💯

**Comment by timvermeulen** [comment]
The single message endpoint doesn't seem to work using https://luath.org.

**Comment by kerrmarin** [comment]
Hey @timvermeulen can you point me to the URL you are trying that isn't working, the message endpoint seems to be working fine for me over SSL e.g.: https://luath.org/api/v1/lists/3/messages/998AF57B-27D9-49E0-B867-D826561E32C8@mac.com

**Comment by timvermeulen** [comment]
I'm not sure which URL I was using, but all I try now work! So maybe I messed up something else. 🙂

**Comment by kerrmarin** [comment]
Luath is now available over SSL on both www and non-www. Thanks for everyone's help!

**Comment by timvermeulen** [comment]
Was the intent to not allow http anymore? It took me a fair bit to realise why my code wasn't working anymore 🙂

**Comment by kerrmarin** [comment]
Hey @timvermeulen, yes it was, sorry!
